### ISSUE TITLE
Support for Video Shorts and Yappy videos?

### ISSUE THREAD

**Issue by yarodevuci** [Valentin-Butorin/rutube_downloader#1]
Hi, thanks for sharing the code, i wonder you can add other videos support? also many regular videos return 404 errors and can not be downloaded ...

**Comment by yarodevuci** [comment]
@Valentin-Butorin  буду признателен за совет

**Comment by Valentin-Butorin** [comment]
> Hi, thanks for sharing the code, i wonder you can add other videos support? also many regular videos return 404 errors and can not be downloaded ...

Hi, thank you for your feedback.
I fixed 404 and added Yappy support. Please check v0.0.2.

**Comment by yarodevuci** [comment]
> > Hi, thanks for sharing the code, i wonder you can add other videos support? also many regular videos return 404 errors and can not be downloaded ...
> 
> Hi, thank you for your feedback. I fixed 404 and added Yappy support. Please check v0.0.2.

Thanks so much!! works like a charm now! Will same logic apply to https://rutube.ru/shorts?

**Comment by Valentin-Butorin** [comment]
> Will same logic apply to https://rutube.ru/shorts?

The logic that applies to shorts is similar to the logic that applies to regular videos. But with minor corrections.
I added this to v0.0.3. Please check and let me know.

**Comment by yarodevuci** [comment]
Thank you again! all sorted.
