### ISSUE TITLE
No longer Works

### ISSUE THREAD

**Issue by yarodevuci** [Valentin-Butorin/rutube_downloader#3]
@Valentin-Butorin 
https://rutube.ru/video/9c9a87a05f9226ccf34484c1932657a3/

`0, message='', url=URL('https://cdn-gcore-1.rutube.ru/hls-vod/9PgfxId5EWUCuPQnOojG3g/1722224581/1877/0x5000c500f1e04c50/82bb4ba3aa2b4a0c8f710e59ec016e4e.mp4.m3u8?i=1920x1080_3755')`

Here is another base_path
'https://salam-2.rutube.ru/dive/river-3-319.rutube.ru/RXci_IPG6FKMdE4poO1Y3A/hls-vod/HE9HKPX569X41d4x__TkWw/1722224732/2173/0x5000c500e7527fb4/42da020275164ad4a022dc92f8057012.mp4.m3u8?i=856x464_109'

I tried adding headers and that did not helped either

It crashes in get_segment_urls

I have also tried with httpx and asyncClient but no luck either...

**In Postman I am able to get a response...**

**Comment by yarodevuci** [comment]
@Valentin-Butorin are you able to take a look?

**Comment by Valentin-Butorin** [comment]
@yarodevuci Hi!
Fixed segment urls in v0.0.4.
The reserve url is now used when base url is not available.
But it's still not a guarantee, especially if you are not in Russia.

**Comment by yarodevuci** [comment]
Got it! Thanks again for following up
