### ISSUE TITLE
Please, make downloader call more frendly by allowing to select resolution

### ISSUE THREAD

**Issue by dmiandr** [Valentin-Butorin/rutube_downloader#6]
Calling sample in readme file is too brief, and main incovenience is that by default greatest resolution is selected, video files becomes very big without any necessity. Can you add something like:
```
import pyinputplus as pyinp

numres = len(rt.playlist._playlist)
print(rt.playlist._playlist[0]._title)
chnum = 0
for res in rt.playlist:
    rcur = str(res._resolution[0]) + "x" + str(res._resolution[1])
    print("(" + str(chnum) + ") - " + rcur)
    chnum+=1

resvar = pyinp.inputInt(prompt="Select resolution to download: ", min=0, max=numres)

rt.playlist[resvar].download()
```

Or, may be add such caller to the project as a separate file?

**Comment by Valentin-Butorin** [comment]
@dmiandr Hi!
You can try v0.0.7.

Now you can get a video with specific resolution:
`rt.get_by_resolution(720)`
And get a list of available resolutions:
`rt.available_resolutions` returns `[480, 720, ...]`

So, in your script, you can input resolution like 1080, 720, etc.:
```python
res_list = list(map(str, rt.available_resolutions))
resvar = pyinp.inputChoice(
    res_list,
    prompt=f"Select resolution between {', '.join(res_list)}: ",
    postValidateApplyFunc=lambda x: rt.get_by_resolution(x)  # returns RutubeVideo object
)
resvar.download()
```
Or something like your code:
```python
print(rt._title)
print('\n'.join([f'({i}) - {v.resolution}' for i, v in enumerate(rt.playlist)]))
resvar = pyinp.inputInt(
    prompt="Select resolution to download: ",
    max=len(rt.playlist),
    applyFunc=int,
    postValidateApplyFunc=lambda x: rt.playlist[x]  # returns RutubeVideo object
)
resvar.download()
```
Or with inputMenu:
```python
resvar = pyinp.inputMenu(
    list(map(str, rt.available_resolutions)),
    prompt='Select resolution to download:\n',
    numbered=True,
)
rt.get_by_resolution(resvar)
```

Also you can download faster with argument `workers` in `download()` method:
`rt.get_by_resolution(720).download(workers=8)`
But it produces high CPU load. You should find the right number of workers for you.
