### ISSUE TITLE
please make download only audio

### ISSUE THREAD

**Issue by SergeyNaumov** [Valentin-Butorin/rutube_downloader#9]
please make download only audio

**Comment by Valentin-Butorin** [comment]
Right now there is no way to download just the audio track. So the only option is to download chunks of video, convert them to audio with ffmpeg and save them to a file. That doesn't make any sense. You will still get the same amount of traffic that way.

So you can easily use ffmpeg, for example:
`ffmpeg -i source_video.mp4 -vn -ar 44100 -ac 2 -ab 320K -f mp3 audio.mp3`
